export const PKG_PREFIX = '@element-ai-vue'
export const PKG_NAME = 'element-ai-vue'
export const PKG_CAMELCASE_NAME = 'ElementAiVue'
export const PKG_CAMELCASE_LOCAL_NAME = 'ElementAiVueLocale'
export const PKG_BRAND_NAME = 'Element Ai Vue'
